/* Auto-generated by: https://github.com/OmnomnomTee/gltfvue Command: npx gltfvue@0.1.0 hyperhumancow.glb */

<script setup>
import { useGLTF } from '@tresjs/cientos'

const { nodes, materials } = await useGLTF('/hyperhumancow.glb')
</script>

<template>
  <TresGroup>
    <TresGroup>
      <TresMesh :geometry="nodes.model.geometry" :material="nodes.model.material" :rotation="[Math.PI / 2, 0, 0]" />
    </TresGroup>
  </TresGroup>
</template>

// useGLTF.preload('/hyperhumancow.glb')
